recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: feather_azure_deployment
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
assistant_id: 20250317-120259-medium-flora
